version = 0.1

[default]
[default.build]
[default.build.parameters]
template = "deploy/aws/template.yaml"

[default.deploy]
[default.deploy.parameters]
stack_name     = "enkan-todo"
resolve_s3     = true
s3_prefix      = "enkan-todo"
region         = "ap-northeast-1"
confirm_changeset = true
capabilities   = "CAPABILITY_IAM"

[native]
[native.build]
[native.build.parameters]
template = "deploy/aws/template-native.yaml"

[native.deploy]
[native.deploy.parameters]
stack_name     = "enkan-todo-native"
resolve_s3     = true
s3_prefix      = "enkan-todo-native"
region         = "ap-northeast-1"
confirm_changeset = true
capabilities   = "CAPABILITY_IAM"
